version: '3'

services:
    ghost:
        image: ghost:5.71-alpine
        container_name: ghost-app-wlog
        volumes:
            - ./:/var/lib/ghost/content/themes/wlog:Z
            - ./data:/var/lib/ghost/content/data/:Z
        environment:
            NODE_ENV: development
            database__client: sqlite3
            database__connection__filename: content/data/ghost.db
        ports:
            - 2368:2368
